"""Add Latitude and Longitude to User

Revision ID: 0ea0b83a05b3
Revises: 
Create Date: 2026-03-11 14:05:04.480791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ea0b83a05b3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('Latitude', sa.String(), nullable=True))
    op.add_column('users', sa.Column('Longitude', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'Longitude')
    op.drop_column('users', 'Latitude')
    # ### end Alembic commands ###
