"""add sender and receiver coordinates to transfer

Revision ID: b01d6f50a3e0
Revises: 0ea0b83a05b3
Create Date: 2026-03-11 14:45:35.126064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b01d6f50a3e0'
down_revision: Union[str, Sequence[str], None] = '0ea0b83a05b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfers', sa.Column('sender_latitude', sa.String(), nullable=True))
    op.add_column('transfers', sa.Column('sender_longitude', sa.String(), nullable=True))
    op.add_column('transfers', sa.Column('receiver_latitude', sa.String(), nullable=True))
    op.add_column('transfers', sa.Column('receiver_longitude', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transfers', 'receiver_longitude')
    op.drop_column('transfers', 'receiver_latitude')
    op.drop_column('transfers', 'sender_longitude')
    op.drop_column('transfers', 'sender_latitude')
    # ### end Alembic commands ###
